#!/usr/bin/python
import requests, time
from flask import Flask, jsonify
from multiprocessing import Process, Value, Array
import serial
from controllers import led
from controllers import lcd

print led
app = Flask(__name__)

front_anim_on = Value('b', True)
front_anim_command = Value('i', 0)
serial_on = False

tasks = [
    {
        'id': 1,
        'title': u'Buy groceries',
        'description': u'Milk, Cheese, Pizza, Fruit, Tylenol',
        'done': False
    },
    {
        'id': 2,
        'title': u'Learn Python',
        'description': u'Need to find a good Python tutorial on the web',
        'done': False
    }
]

hue = 0


@app.route('/api/AT/1', methods=['GET'])
def fakeAT():
    hue = hue + 1
    return jsonify({'hue': hue})


@app.route('/api', methods=['GET'])
def get_tasks():
    return jsonify({'tasks': tasks})


framerate = 1/60.0
def render_thread(front_anim_on, front_anim_command ):
    print "RENDER STARTING"
    while True:
        renderStart = time.time()
        lcd.main()
        led.main(front_anim_on, front_anim_command)
        renderTime = time.time() - renderStart
        if renderTime < framerate:
            time.sleep(framerate - renderTime)
        #else:
        #    print "framedrop... render took:"+str(renderTime)+">"+str(framerate)


def serial_thread(serial_on, ):
    print "SERIAL STARTING"
    if serial_on.value == 1:
        print "SERIAL START"
        ser = serial.Serial('/dev/ttyGS0', 115200)
        print("serial ready")
        ser.write("+READY")
        while True:
            command = ser.read()
            ser.write(command)
            print(command)
            r = requests.get('http://127.0.0.1:5000/api/AT/'+command)
            print(r.status_code)


if __name__ == "__main__":
    if serial_on:
        serial_p = Process(target=serial_thread, args=(serial_on,))
        serial_p.start()
    render_p = Process(target=render_thread, args=(front_anim_on, front_anim_command))
    render_p.start()
    if serial_on:
        serial_p.join()
    render_p.join()
    app.run(debug=True, use_reloader=False, host='0.0.0.0')
